services:
  rstudio:
    image: kevinl002/dsci-310-group-05-container
    ports:
      - "8787:8787"
      - "8888:8888"
    environment:
      - PASSWORD=password  # Set password (password)
      - USER=rstudio  # Set username (rstudio)
    volumes:
      - .:/home/rstudio/project  # Mount the current directory
    working_dir: /home/rstudio/project  # Set working directory
    restart: unless-stopped
