services:
  rstudio:
    image: rocker/rstudio:4.4.2
    ports:
      - "8787:8787"
      - "8888:8888"
    environment:
      - PASSWORD=password  # Set a password for RStudio login
      - USER=rstudio  # Username (set to 'rstudio')
    volumes:
      - .:/home/rstudio/project  # Mount the current directory
    working_dir: /home/rstudio/project  # Set working directory
    restart: unless-stopped
