<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nika Karimi Seffat, Ethan Wang, Gautam Arora and Kevin Li">

<title>DSCI 310 Project: Group 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DSCI 310 Project: Group 5</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nika Karimi Seffat, Ethan Wang, Gautam Arora and Kevin Li </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Outline</h2>
   
  <ul>
  <li><a href="#car-evaluation-analysis" id="toc-car-evaluation-analysis"><span class="header-section-number">1</span> <strong>Car Evaluation Analysis</strong></a>
  <ul>
  <li><a href="#summary" id="toc-summary"><span class="header-section-number">1.1</span> <strong>Summary</strong></a></li>
  <li><a href="#introduction" id="toc-introduction"><span class="header-section-number">1.2</span> <strong>Introduction</strong></a></li>
  <li><a href="#methods-and-results" id="toc-methods-and-results"><span class="header-section-number">1.3</span> <strong>Methods and Results</strong></a>
  <ul>
  <li><a href="#data-loading" id="toc-data-loading"><span class="header-section-number">1.3.1</span> <strong>Data Loading</strong></a></li>
  <li><a href="#data-wrangling-and-cleaning" id="toc-data-wrangling-and-cleaning"><span class="header-section-number">1.3.2</span> <strong>Data Wrangling and Cleaning</strong></a></li>
  <li><a href="#data-types" id="toc-data-types"><span class="header-section-number">1.3.3</span> <strong>Data Types</strong></a></li>
  <li><a href="#summary-of-data" id="toc-summary-of-data"><span class="header-section-number">1.3.4</span> <strong>Summary of Data</strong></a></li>
  <li><a href="#eda-analysis---visualization" id="toc-eda-analysis---visualization"><span class="header-section-number">1.3.5</span> <strong>EDA Analysis - Visualization</strong></a></li>
  <li><a href="#knn-classification-analysis" id="toc-knn-classification-analysis"><span class="header-section-number">1.3.6</span> <strong>kNN Classification Analysis</strong></a></li>
  <li><a href="#visualization-of-analysis" id="toc-visualization-of-analysis"><span class="header-section-number">1.3.7</span> <strong>Visualization of Analysis</strong></a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion"><span class="header-section-number">1.4</span> <strong>Discussion</strong></a>
  <ul>
  <li><a href="#what-we-found" id="toc-what-we-found"><span class="header-section-number">1.4.1</span> <strong>What We Found</strong></a></li>
  <li><a href="#potential-impact" id="toc-potential-impact"><span class="header-section-number">1.4.2</span> <strong>Potential Impact</strong></a></li>
  <li><a href="#future-questions" id="toc-future-questions"><span class="header-section-number">1.4.3</span> <strong>Future Questions</strong></a></li>
  </ul></li>
  <li><a href="#references" id="toc-references"><span class="header-section-number">1.5</span> <strong>References</strong></a></li>
  </ul></li>
  </ul>
</nav>
<section id="car-evaluation-analysis" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> <strong>Car Evaluation Analysis</strong></h1>
<section id="summary" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">1.1</span> <strong>Summary</strong></h2>
<p>This project analyzes the <strong>Car Evaluation Dataset</strong> from <span class="citation" data-cites="UCI1988">UCI Machine Learning Repository (<a href="#ref-UCI1988" role="doc-biblioref">1988</a>)</span>, which contains 1728 with <strong>six categorical attributes: buying price</strong>, maintenance cost, number of doors, passenger capacity, luggage space, and safety rating. The dataset was clean, with no missing values or duplicates, and required <strong>ordinal encoding</strong> for machine learning analysis.</p>
<p>Exploratory Data Analysis (EDA) revealed balanced distributions across most features. However, the “class” variable was highly imbalanced, with “unacceptable” accounting for 1210 instances and “very good” only 65 instances. The k-Nearest Neighbors (kNN) model was trained to predict <strong>safety levels</strong> using the other features, achieving an accuracy of 44.06% with an optimal k of 19—an improvement over random guessing (33.33%) but highlighting the model’s limited predictive power.</p>
<p>The findings indicate that individual features do not strongly determine safety levels independently, suggesting the need for more complex models or additional variables. These results have implications for both vehicle safety assessment and methodological best practices in categorical data analysis, reinforcing the importance of feature selection and encoding techniques for machine learning applications.</p>
</section>
<section id="introduction" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1.2</span> <strong>Introduction</strong></h2>
<p>###<strong>Background</strong>:</p>
<p>Cars and personal transportation are an inevitable part of everyday life in the developed world. They play a crucial role in people’s daily routines, enabling them to commute to work, travel, attend social gatherings, and explore new places. However, cars also pose significant safety risks. In 2023 alone, car accidents accounted for over 40 000 fatailities (<span class="citation" data-cites="Wikipedia2019">Wikipedia Contributors (<a href="#ref-Wikipedia2019" role="doc-biblioref">2019</a>)</span>). Given these risks, it is no surprise that many individuals seek ways to make car travel safer while maintaining its convenience and necessity.</p>
<p>Research has shown that consumers are willing to invest in vehicle safety. For example, <span class="citation" data-cites="Andersson2008">Andersson (<a href="#ref-Andersson2008" role="doc-biblioref">2008</a>)</span> found that Swedish drivers were willing to pay a premium for improved car design and build quality to reduce the risk of injury in accidents. Additionally, design and material choices play a critical role in determining a vehicle’s safety. <span class="citation" data-cites="Nygren1983">Nygren (<a href="#ref-Nygren1983" role="doc-biblioref">1983</a>)</span> found that factors such as a car’s weight, seatbelt design, and headrests significantly influenced accident survivability. More recently, <span class="citation" data-cites="Richter2005">Richter et al. (<a href="#ref-Richter2005" role="doc-biblioref">2005</a>)</span> demonstrated that passive safety improvements—such as enhanced structural integrity and interior design modifications—have contributed to a measurable decline in injury rates from car accidents. These findings highlight the importance of identifying key factors that contribute to vehicle safety.</p>
<p>Given this context, our research project aims to answer the following question:</p>
<p><strong>Can we predict the estimated safety of a car using various attributes, such as its buying price, capacity (persons), and maintenance cost?</strong></p>
<p>To answer this question, we will use the Car Evaluation Dataset from UC Irvine’s Machine Learning Repository. This multivariate classification dataset contains six car design and classification variables, and includes 1728 observations. Key variables that will be central to our analysis include the car’s buying price, maintenance cost, seating capacity (in terms of the number of passengers it can accommodate), and the car’s evaluation level (categorized as unacceptable, acceptable, good, or very good).</p>
</section>
<section id="methods-and-results" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="methods-and-results"><span class="header-section-number">1.3</span> <strong>Methods and Results</strong></h2>
<section id="data-loading" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="data-loading"><span class="header-section-number">1.3.1</span> <strong>Data Loading</strong></h3>
<p>The dataset was retrieved from an online source and loaded into R for analysis using the read.csv function. This dataset contains categorical variables describing various attributes of cars, which will be used for classification.</p>
<div id="tbl-data" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Data-Preview
</figcaption>
<div aria-describedby="tbl-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>     V1    V2 V3 V4    V5   V6    V7
1 vhigh vhigh  2  2 small  low unacc
2 vhigh vhigh  2  2 small  med unacc
3 vhigh vhigh  2  2 small high unacc
4 vhigh vhigh  2  2   med  low unacc
5 vhigh vhigh  2  2   med  med unacc
6 vhigh vhigh  2  2   med high unacc</code></pre>
</div>
</div>
</figure>
</div>
<p>Although the dataset comes with predefined columns, it does not include column names when we read in the CSV file. We manually assign meaningful column names based on the UCI dataset documentation. <a href="#tbl-col" class="quarto-xref">Table&nbsp;2</a></p>
<div id="tbl-col" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-col-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Assigning the column names
</figcaption>
<div aria-describedby="tbl-col-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>  buying maint doors persons lug_boot safety class
1  vhigh vhigh     2       2    small    low unacc
2  vhigh vhigh     2       2    small    med unacc
3  vhigh vhigh     2       2    small   high unacc
4  vhigh vhigh     2       2      med    low unacc
5  vhigh vhigh     2       2      med    med unacc
6  vhigh vhigh     2       2      med   high unacc</code></pre>
</div>
</div>
</figure>
</div>
</section>
<section id="data-wrangling-and-cleaning" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="data-wrangling-and-cleaning"><span class="header-section-number">1.3.2</span> <strong>Data Wrangling and Cleaning</strong></h3>
<div id="tbl-nan" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-nan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Count of Missing and Duplicate Values
</figcaption>
<div aria-describedby="tbl-nan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>                       Label Value
1   Number of Missing Values     0
2 Number of Duplicate Values     0</code></pre>
</div>
</div>
</figure>
</div>
<p>Amazing! No missing values and duplicate rows. <a href="#tbl-nan" class="quarto-xref">Table&nbsp;3</a></p>
</section>
<section id="data-types" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="data-types"><span class="header-section-number">1.3.3</span> <strong>Data Types</strong></h3>
<p>Since k-Nearest Neighbors (kNN) is a distance-based algorithm, it requires numerical input for feature comparisons. However, our dataset currently consists of categorical variables (all factors in R).</p>
<div id="tbl-enc" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-enc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Car Data Encoded
</figcaption>
<div aria-describedby="tbl-enc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>  buying maint doors persons lug_boot safety class
1      4     4     2       2        1      1     1
2      4     4     2       2        1      2     1
3      4     4     2       2        1      3     1
4      4     4     2       2        2      1     1
5      4     4     2       2        2      2     1
6      4     4     2       2        2      3     1</code></pre>
</div>
</div>
</figure>
</div>
<p><strong>Since we converted the text into numerical variables, we have attached the description of each numerical value per feature below for reference:</strong></p>
<p><strong><code>buying</code> and <code>maint</code></strong> - low: 1 - med: 2 - high: 3 - vhigh: 4</p>
<p><strong><code>doors</code> and <code>persons</code></strong> - The values are technically numerical, but they only fall into 3 or 4 categories and are not continuous.</p>
<p><strong><code>lug_boot</code> and <code>safety</code></strong> - small/low: 1 - med: 2 - big/high: 3</p>
<p><strong><code>class</code></strong> - unacc (unacceptable): 1 - acc (acceptable): 2 - good: 3 - vgood: 4</p>
<p><strong>The data has been cleaned and is ready for analysis!</strong></p>
</section>
<section id="summary-of-data" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="summary-of-data"><span class="header-section-number">1.3.4</span> <strong>Summary of Data</strong></h3>
<div id="tbl-sum" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Summary Statistics
</figcaption>
<div aria-describedby="tbl-sum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>     buying         maint          doors         persons         lug_boot
 Min.   :1.00   Min.   :1.00   Min.   :2.00   Min.   :2.000   Min.   :1  
 1st Qu.:1.75   1st Qu.:1.75   1st Qu.:2.75   1st Qu.:2.000   1st Qu.:1  
 Median :2.50   Median :2.50   Median :3.50   Median :4.000   Median :2  
 Mean   :2.50   Mean   :2.50   Mean   :3.50   Mean   :3.667   Mean   :2  
 3rd Qu.:3.25   3rd Qu.:3.25   3rd Qu.:4.25   3rd Qu.:5.000   3rd Qu.:3  
 Max.   :4.00   Max.   :4.00   Max.   :5.00   Max.   :5.000   Max.   :3  
     safety      class      
 Min.   :1   Min.   :1.000  
 1st Qu.:1   1st Qu.:1.000  
 Median :2   Median :1.000  
 Mean   :2   Mean   :1.415  
 3rd Qu.:3   3rd Qu.:2.000  
 Max.   :3   Max.   :4.000  </code></pre>
</div>
</div>
</figure>
</div>
<div id="tbl-cnt" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cnt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Unique Occurrences Count
</figcaption>
<div aria-describedby="tbl-cnt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 3
   Variable Value Count
   &lt;chr&gt;    &lt;dbl&gt; &lt;int&gt;
 1 buying       1   432
 2 buying       2   432
 3 buying       3   432
 4 buying       4   432
 5 class        1  1210
 6 class        2   384
 7 class        3    69
 8 class        4    65
 9 doors        2   432
10 doors        3   432
11 doors        4   432
12 doors        5   432
13 lug_boot     1   576
14 lug_boot     2   576
15 lug_boot     3   576
16 maint        1   432
17 maint        2   432
18 maint        3   432
19 maint        4   432
20 persons      2   576
21 persons      4   576
22 persons      5   576
23 safety       1   576
24 safety       2   576
25 safety       3   576</code></pre>
</div>
</div>
</figure>
</div>
<p><a href="#tbl-cnt" class="quarto-xref">Table&nbsp;6</a> provides a clearer picture of the dataset’s distribution across categorical variables. The <code>buying</code>, <code>maint</code>, and <code>doors</code> features all have an even distribution, with each level appearing 432 times, suggesting a balanced dataset for these features. The <code>safety</code>, <code>lug_boot</code> and <code>persons</code> features are also evenly distributed across its three levels, with 576 occurrences each, ensuring no significant class imbalance in this variable. However, the <code>class</code> is highly imbalanced, with “unacc” (encoded as 1) making up the majority (1210 occurrences), while “vgood” (encoded as 4) is rare (only 65 occurrences). Since we are not using the <code>class</code> variable in our analysis, this is not much of a concern.</p>
<p><strong>Our x and y variables all have sufficient data points for analysis!</strong></p>
</section>
<section id="eda-analysis---visualization" class="level3" data-number="1.3.5">
<h3 data-number="1.3.5" class="anchored" data-anchor-id="eda-analysis---visualization"><span class="header-section-number">1.3.5</span> <strong>EDA Analysis - Visualization</strong></h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-buy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-buy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-buy-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-buy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of Buying Price by Safety Level
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-num" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-num-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distribution of Number of Persons by Safety Level
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-main" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-main-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-main-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-main-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Distribution of Maintenance Cost by Safety Level
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Histograms of Safety Across 3 Input Variables: Buying Price, Capacity (Number of Persons), and Maintenance Cost</strong></p>
<p>As we saw in the summary table, all the safety levels are evenly distributed across each of the independent variables.</p>
<p><strong>Initial Observations</strong></p>
<p>The histograms indicate that the safety levels (<a href="#fig-buy" class="quarto-xref">Figure&nbsp;1</a>, <a href="#fig-num" class="quarto-xref">Figure&nbsp;2</a>, and <a href="#fig-main" class="quarto-xref">Figure&nbsp;3</a>) are evenly distributed across all three independent variables: buying price, number of persons, and maintenance cost. This suggests that the dataset is well-balanced with respect to safety levels, meaning that safety is not disproportionately concentrated in any particular category of these features. However, we do not observe significant variation is observed in the distribution of safety across these variables.</p>
<p><strong>Proceeding with Analysis</strong></p>
<p>While individual variables may not show a strong distinction in safety levels on their own, the interaction between multiple features could still be meaningful for classification. Just because safety is evenly distributed across each independent variable separately doesn’t mean that a combination of factors (e.g., high buying price + low maintenance + more persons) won’t reveal patterns that help predict safety levels.</p>
</section>
<section id="knn-classification-analysis" class="level3" data-number="1.3.6">
<h3 data-number="1.3.6" class="anchored" data-anchor-id="knn-classification-analysis"><span class="header-section-number">1.3.6</span> <strong>kNN Classification Analysis</strong></h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Best k found through cross-validation: 17 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Best cross-validation accuracy: 47.22 %</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Test Set Accuracy: 46.09 %</code></pre>
</div>
</div>
<p>The final kNN model achieved 46.09% accuracy, which is somewhat reflective of the CV accuracy of 47.22%. This is not a great accuracy, but it’s better than random guessing, which would be 33.33%.</p>
</section>
<section id="visualization-of-analysis" class="level3" data-number="1.3.7">
<h3 data-number="1.3.7" class="anchored" data-anchor-id="visualization-of-analysis"><span class="header-section-number">1.3.7</span> <strong>Visualization of Analysis</strong></h3>
<p>Since we are using multiple input variables for our kNN classification, it wouldn’t be possible to graph it out 2D. We will do a <strong>confusion matrix</strong> as our visualization.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-conf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-conf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-conf-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-conf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Confusion Matrix to Evaluate Model Performance
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Heatmap of Confusion Matrix for Visualization of Analysis</strong></p>
</section>
</section>
<section id="discussion" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="discussion"><span class="header-section-number">1.4</span> <strong>Discussion</strong></h2>
<section id="what-we-found" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="what-we-found"><span class="header-section-number">1.4.1</span> <strong>What We Found</strong></h3>
<p>The analysis started with a car evaluation dataset lacking column names, which were manually assigned as “buying,” “maint,” “doors,” “persons,” “lug_boot,” “safety,” and “class” based on UCI documentation. The dataset, comprising 1728 rows, was clean with no missing values or duplicates. All variables were categorical and ordinal, necessitating ordinal encoding into numerical values for k-Nearest Neighbors (kNN) analysis. Summary statistics revealed balanced distributions across most features (e.g., “buying,” “maint,” “doors,” “lug_boot,” “safety,” and “persons”), with each category appearing 432 or 576 times. However, the “class” variable was highly imbalanced, with “unacc” dominating (1210 instances) and “vgood” rare (65 instances), though this was irrelevant as “class” was not used in the kNN analysis.</p>
<p>Exploratory Data Analysis (EDA) using histograms showed that “safety” levels (low, medium, high) were evenly distributed across “buying,” “persons,” and “maint,” indicating no single feature strongly distinguished safety levels independently. The kNN model, trained to predict “safety” using other features, achieved a final accuracy of 46.09% with an optimal k of 17, surpassing random guessing (33.33% for three classes) but suggesting limited predictive power. A confusion matrix heatmap visualized the model’s performance, highlighting prediction accuracies and errors across safety levels.</p>
<p>The dataset’s cleanliness and balanced feature distributions partially aligned with expectations, given its UCI origin, known for structured datasets. The absence of missing values and duplicates was anticipated, simplifying preprocessing. However, the uniform distribution of “safety” across individual features was unexpected. Real-world data might show biases—e.g., higher safety with lower buying prices or higher maintenance costs due to safety features—yet this dataset lacked such trends, possibly indicating synthetic balancing for algorithmic testing.</p>
<p>The kNN accuracy of 46.09% was lower than ideal but not surprising. The even distribution of safety and lack of strong individual predictors suggested that kNN, reliant on feature proximity, might struggle. The slight accuracy increase to 47.22% from 46.09% with tuning was expected, though the overall modest performance hinted at complex feature interactions or insufficient predictive signals, aligning with the EDA findings.</p>
</section>
<section id="potential-impact" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="potential-impact"><span class="header-section-number">1.4.2</span> <strong>Potential Impact</strong></h3>
<p>These results have practical and methodological implications. The preprocessing and encoding workflow offers a replicable approach for handling ordinal categorical data, applicable to fields like healthcare or marketing. The balanced predictors ensure unbiased model training, making this dataset a fair benchmark for algorithmic evaluation.</p>
<p>However, the kNN’s 46.09% accuracy limits its utility for real-world safety prediction, such as in automotive design or consumer decisions, where higher reliability is critical. The uniform safety distribution suggests unmeasured variables or interactions influence safety, necessitating richer data or advanced models for practical use. This finding could prompt researchers to refine feature selection or engineering strategies when using distance-based methods, influencing future dataset analyses.</p>
</section>
<section id="future-questions" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="future-questions"><span class="header-section-number">1.4.3</span> <strong>Future Questions</strong></h3>
<p>The analysis raises several questions for further exploration each aiming to enhance its practical and analytical value:</p>
<ol type="1">
<li><p><strong>Incorporating Additional Car Attributes</strong>: Could adding car-specific variables—like crash test scores, manufacturing year, or brand reputation—enhance safety predictions? Expanding the dataset with real-world metrics, such as fuel efficiency, engine type (e.g., electric vs.&nbsp;gasoline), or historical recall data, might improve its utility for buyers or manufacturers. For instance, integrating standardized safety ratings (e.g., IIHS or NHTSA scores) could boost model accuracy beyond 46.09, while manufacturing year might highlight safety evolution, and brand reputation could reflect quality consistency. This could transform the dataset into a robust tool for practical car evaluation.</p></li>
<li><p><strong>Consumer Preferences and Safety Trade-offs</strong>: How do car features like buying price or maintenance cost influence consumer perceptions of safety versus affordability? Survey data or X post analysis could reveal if buyers prioritize low-cost options over safety, guiding how manufacturers balance these factors in car design.</p></li>
<li><p><strong>Environmental Impact on Car Safety</strong>: Could environmental factors, such as typical driving conditions (urban vs.&nbsp;rural) or climate (e.g., snowy regions), affect safety ratings in this dataset? Linking car attributes to usage contexts might show if features like luggage boot size or door count adapt to safety needs in diverse settings.</p></li>
<li><p><strong>Temporal Dynamics of Car Evaluation</strong>: How would safety predictions change if the dataset tracked cars over time, such as pre- and post-safety regulation changes? A longitudinal approach could assess if older cars with fewer doors or lower safety ratings become outliers as standards evolve.</p></li>
<li><p><strong>Cross-Cultural Car Evaluation</strong>: Do safety priorities differ across regions (e.g., North America vs.&nbsp;Europe vs.&nbsp;Asia), and how might this dataset adapt? Incorporating regional safety standards or car preferences (e.g., compact cars in Europe) could test its global applicability, revealing cultural influences on car evaluation.</p></li>
<li><p><strong>Feature Interactions in Car Evaluation</strong>: Could combining car features like buying price and maintenance cost reveal stronger predictors of safety ratings? Exploring interaction terms (e.g., high buying price with low maintenance) might uncover patterns that influence car safety assessments more effectively, such as whether cost trade-offs correlate with safety compromises.</p></li>
<li><p><strong>Alternative Models for Car Safety Prediction</strong>: Would advanced models like random forests or neural networks outperform kNN by identifying critical car features—like luggage boot size or passenger capacity—for safety prediction? These could reveal non-linear relationships, such as how larger boot sizes might indicate family-oriented designs with higher safety standards.</p></li>
</ol>
<p>In conclusion, this study establishes a foundation for analyzing categorical datasets with kNN, while highlighting limitations and inspiring future research into feature engineering, model selection, and practical applicability in car evaluation contexts.</p>
</section>
</section>
<section id="references" class="level2 unnumbered" data-number="1.5">


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">1.5 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Andersson2008" class="csl-entry" role="listitem">
Andersson, H. 2008. <span>“Willingness to Pay for Car Safety: Evidence from Sweden.”</span> <em>Environmental and Resource Economics</em> 41: 579–94.
</div>
<div id="ref-Nygren1983" class="csl-entry" role="listitem">
Nygren, Å. 1983. <span>“Injuries to Car Occupants—Some Aspects of the Interior Safety of Cars: A Study of a Five-Year Material from an Insurance Company.”</span> <em>Acta Oto-Laryngologica</em> 95 (sup395): 1–135.
</div>
<div id="ref-Richter2005" class="csl-entry" role="listitem">
Richter, M., H. C. Pape, D. Otte, and C. Krettek. 2005. <span>“Improvements in Passive Car Safety Led to Decreased Injury Severity–a Comparison Between the 1970s and 1990s.”</span> <em>Injury</em> 36 (4): 484–88.
</div>
<div id="ref-UCI1988" class="csl-entry" role="listitem">
UCI Machine Learning Repository. 1988. <span>“Car Evaluation.”</span> <a href="https://archive.ics.uci.edu/dataset/19/car+evaluation">https://archive.ics.uci.edu/dataset/19/car+evaluation</a>.
</div>
<div id="ref-Wikipedia2019" class="csl-entry" role="listitem">
Wikipedia Contributors. 2019. <span>“Motor Vehicle Fatality Rate in u.s. By Year.”</span> Wikipedia; Wikimedia Foundation. <a href="https://en.wikipedia.org/wiki/Motor_vehicle_fatality_rate_in_U.S._by_year">https://en.wikipedia.org/wiki/Motor_vehicle_fatality_rate_in_U.S._by_year</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>